name: rainbow_vis
version: 2.0.0
description: Color data visualization; easily map numerical domain to a smooth-transitioning color range.
homepage: https://github.com/ilikerobots/rainbowvis-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.6.0
