name: rainbow_vis
version: 1.0.0
description: Color data visualization; easily map numbers to a smooth-transitioning color legend.
author: Mike Hoolehan <mike@hoolehan.com>
homepage: https://github.com/ilikerobots/rainbowvis-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  effective_dart: ^1.0.0
  test: ^1.6.0
